route:
  group_by: ["instance", "job", "pod"]

  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

  receiver: discord

templates:
  # templates in french for discord notifications
  - discord_fr.tmpl

receivers:
  - name: discord
    discord_configs:
      - webhook_url: <WEBHOOK_URL>
