route:
  group_by: ['instance', 'job', 'pod']

  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

  receiver: discord

receivers:
- name: discord
  discord_configs:
  - webhook_url: <WEBHOOK_URL>