services:
  pokedex:
    image: hexagone/pokedex
    build:          
      context: pokedex
    hostname: pokedex
    container_name: pokedex
    restart: unless-stopped
    networks:
      - hexatek
    ports:
      - "8180:80" # WebUI

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    hostname: otel-collector
    container_name: otel-collector
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    networks:
      - hexatek      
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 24317:4317 # OTLP gRPC receiver
      - 24318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
  
networks:
  hexatek:
    name: 02-prometheus-mimir_default
    external: true
