services:
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: unless-stopped
    networks:
      - hexatek
    ports:
      - "9093:9093"
    volumes:
      - "./config:/config"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug

networks:
  hexatek:
    name: 02-prometheus-mimir_default
    external: true

volumes:
  alertmanager-data: