services:
  alertmanager:
    image: prom/alertmanager
    hostname: alertmanager
    container_name: alertmanager
    restart: unless-stopped
    networks:
      - hexatek
    ports:
      - "9093:9093"
    volumes:
      - "./config/alertmanager.yml:/config/alertmanager.yml"
      - "./config/discord_webhook.txt:/config/discord_webhook.txt"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml

networks:
  hexatek:
    name: 02-prometheus-mimir_default
    external: true

volumes:
  alertmanager-data: