receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        include_metadata: true
        cors:
          allowed_origins:
            - "*"
          max_age: 7200

processors:
  batch:

exporters:
  # Traces to jaeger
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Logs to fluentbit
  otlp:
    endpoint: fluentbit-otel:4318
    tls:
      insecure: true    

  # Metrics to prometheus
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: hexatek
  
  debug:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger,debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus,debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,debug]