receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  # Traces to jaeger
  otlp/jaeger:
    endpoint: jaeger:4317

  # Logs to fluentbit
  otlp:
    endpoint: fluentbit-otel:4318

  # Metrics to prometheus
  prometheus:
    endpoint: "localhost:8889"
    namespace: hexatek
  
  debug:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger,debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus,debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,debug]