services:
  jaeger:
    image: jaegertracing/all-in-one
    hostname: jaeger
    container_name: jaeger
    restart: unless-stopped
    networks:
      - hexatek
    ports:
      - "16686:16686" # WebUI
      - "4317:4317"   # OpenTelemetry gRPC
      - "14269:14269" # Admin port (metrics)

  zipkin:
    image: openzipkin/zipkin
    hostname: zipkin
    container_name: zipkin
    restart: unless-stopped
    networks:
      - hexatek
    ports:
      - "9411:9411" # Zipkin port

  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    networks:
      - hexatek
    volumes:
      - ./tempo-data:/var/tempo

  tempo:
    image: *tempoImage
    hostname: tempo
    container_name: tempo
    restart: unless-stopped
    networks:
      - hexatek
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"    # tempo
      - "44317:4317"   # otlp grpc
      - "44318:4318"   # otlp http
      - "19411:9411"   # zipkin
    depends_on:
      - init

networks:
  hexatek:
    name: 02-prometheus-mimir_default
    external: true
